stages:
  - build

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin
  script:
    - docker build -t $ACR_LOGIN_SERVER/driverfly-frontend:latest .
    - docker push $ACR_LOGIN_SERVER/driverfly-frontend:latest
  only:
    - main