export enum ApplicantAccordion {
    EMPLOYEE_SS_OR_ID= "EMPLOYEE_SS_OR_ID",
    DISCLOSURE_AND_AUTHORIZATION_DATE= "DISCLOSURE_AND_AUTHORIZATION_DATE",
    IMPORTANT_DISCLOSURE_BACKGROUND_DATE= "IMPORTANT_DISCLOSURE_BACKGROUND_DATE",
    GENERAL_CONSENT= "GENERAL_CONSENT"
}