export enum ApplicantStatus {
    APPLIED = "APPLIED",
    LEAD = "LEAD",
    ACCEPTED = "ACCEPTED",
    SHORTLISTED = "SHORTLISTED",
    INTERVIEWED = "INTERVIEWED",
    REJECTED = "REJECTED",
    HIRED = "HIRED",
    WITHDRAWN = "WITHDRAWN"
}
