export enum ApplicantDocumentType {
  RESUME_OPTIONAL = 'RESUME_OPTIONAL',
  MOTOR_VEHICLE_RECORD_MVR = 'MOTOR_VEHICLE_RECORD_MVR',
  DRIVER_LICENSE = 'DRIVER_LICENSE',
  MEDICAL_EXAMINER_CERTIFICATE_MEDICAL_CARD = 'MEDICAL_EXAMINER_CERTIFICATE_MEDICAL_CARD',
  MEDICAL_EXAMINATION_REPORT_LONG_FORM = "MEDICAL_EXAMINATION_REPORT_LONG_FORM",
  PROOF_OF_INSURANCE = 'PROOF_OF_INSURANCE',
  INSURANCE_CERTIFICATE = 'INSURANCE_CERTIFICATE',
  VEHICLE_TITLE = 'VEHICLE_TITLE',
  EQUIPMENT_LEASE = 'EQUIPMENT_LEASE',
}
