export enum ApplicantAdditionalFilesEnum {
    DAC_REPORT = "DAC_REPORT",
    SKILL_PERFORMANCE_EVALUATION_CERTIFICATE = "SKILL_PERFORMANCE_EVALUATION_CERTIFICATE",
    SIGNED_HOURS_OF_SERVICE_RECORD_STATEMENT = "SIGNED_HOURS_OF_SERVICE_RECORD_STATEMENT"
}