export enum ApplicantVOEFormEnum {
    TYPE_OF_VEHICLE = "type_of_vehicle",
    SAFETY_PERFORMANCE_HISTROY_REPORT="SAFETY_PERFORMANCE_HISTROY_REPORT",
    SUBJECT_TO_TESTS_DOT="SUBJECT_TO_TESTS_DOT"
  }
  