export enum ApplicantDac {
    // PERIOD_OF_SERVICE = 'PERIOD_OF_SERVICE',
    // EQUIPMENT_OPERATED = 'EQUIPMENT_OPERATED',
    // LOADS_HAULED = 'LOADS_HAULED',
    // DRIVER_STATUS_AND_EXPERIENCE = 'DRIVER_STATUS_AND_EXPERIENCE',
    // REASON_FOR_LEAVING = 'REASON_FOR_LEAVING',
    // REHIRE_ELIGIBILITY = 'REHIRE_ELIGIBILITY',
    // NUMBER_OF_ACCIDENTS = 'NUMBER_OF_ACCIDENTS',
    // ACCIDENT_DETAILS = 'ACCIDENT_DETAILS',
    // DRUG_AND_ALCOHOL_HISTORIES = 'DRUG_AND_ALCOHOL_HISTORIES',
    // PRE_EMPLOYMENT_TEST_RESULTS = 'PRE_EMPLOYMENT_TEST_RESULTS',
    // TRUCK_DRIVING_SCHOOL_PERFORMANCE_RECORDS = 'TRUCK_DRIVING_SCHOOL_PERFORMANCE_RECORDS',

    INSURANCE_PASS = "INSURANCE_PASS",
    ORIENTATION_COMPLETE = "ORIENTATION_COMPLETE",
    TRUCK_PROVIDED_OPTIONAL = "TRUCK_PROVIDED_OPTIONAL",

}