export enum ApplicantExtras {
  AUTHORIZE_TO_COMMUNICATE = "AUTHORIZE_TO_COMMUNICATE",
  LINE_ADDRESS = "LINE_ADDRESS",
  QUALIFIED_FOR_MANUAL_TRANSMISSION = "QUALIFIED_FOR_MANUAL_TRANSMISSION",
  CDL_NUMBER = "CDL_NUMBER",
  CURRENT_EMPLOYER = "CURRENT_EMPLOYER",
  PAST_EMPLOYER = "PAST_EMPLOYER",
  ROUTES = "ROUTES",
  REQUIRE_W2_EMPLOYMENT = "REQUIRE_W2_EMPLOYMENT",
  OTHER_ABSOLUTELY_REQUIREMENTS = "OTHER_ABSOLUTELY_REQUIREMENTS",
  ALREADY_APPLIED_TO_COMPANY = "ALREADY_APPLIED_TO_COMPANY",
  ALREADY_WORKED_TO_COMPANY = "ALREADY_WORKED_TO_COMPANY",
  ACCIDENT_DETAILS = "ACCIDENT_DETAILS",
  VIOLATION_DETAILS = "VIOLATION_DETAILS",
  REASON_FOR_UNABLE_TO_PERFORM_JOB = "REASON_FOR_UNABLE_TO_PERFORM_JOB",
  CONVICTED_OF_FELONY = "CONVICTED_OF_FELONY",
  DOT_REGULATION = "DOT_REGULATION",

  // talha's entities
  HEAR_ABOUT_US = "HEAR_ABOUT_US",
  APPLY_DATE = "APPLY_DATE",
  VIOLATION_COUNT = "VIOLATION_COUNT",
  PAST_LICENSE_SUSPENSION = "PAST_LICENSE_SUSPENSION",
}
