export enum ApplicantVoeFormEnum {
  EMPLOYED_BY_US = "EMPLOYED_BY_US",
  WAS_EMPLOYED_AS = "WAS_EMPLOYED_AS",
  TYPE_OF_VEHICLE = "TYPE_OF_VEHICLE",
  SAFETY_PERFORMANCE_HISTROY_REPORT = "SAFETY_PERFORMANCE_HISTROY_REPORT",
  SUBJECT_TO_TESTS_DOT = "SUBJECT_TO_TESTS_DOT",
}
