export enum LicenseRestrictions {
    L_NO_FULL_AIR_BREAK_L = 'L',
    // Z_NO_FULL_AIR_BREAK_L= 'Z',
    E_NO_MANULA_TRANSMISSION = 'E',
    O_NO_FIFTH_WHEEL_CONNECTION = 'O',
    // M_ONLY_CLASS_B_AND_C_PASSENGER_VEHICLE_OR_SCHOOL_BUS = 'M',
    N_ONLY_CLASS_C_PASSENGER_VEHICLE_OR_SCHOOL_BUS = 'N',
    V_MEDICAL_VARIANCE = 'V',
    OTHER = 'OTHER',
}
  