export enum ApplicantEntryMode {
  MANUALLY_ADDED = 'MANUALLY_ADDED',
  COMPANY_UPLOADED = 'COMPANY_UPLOADED',
  DIGITAL_HIRING_APP = 'DIGITAL_HIRING_APP',
  SHORT_FORM_APPLICATION = 'SHORT_FORM_APPLICATION',
  AUTO_RECRUITING_LEAD = 'AUTO_RECRUITING_LEAD',
  ATS_IMPORT = 'ATS_IMPORT',
  FACEBOOK_LEAD = 'FACEBOOK_LEAD',
}
