export enum FlagInappropriateApplicant {
    DRIVER_IS_NOT_WHO_THEY_SAY_THEY_ARE = "DRIVER_IS_NOT_WHO_THEY_SAY_THEY_ARE",
    DRIVER_IS_A_THREAT_TO_THEMSELVES_OR_OTHER = "DRIVER_IS_A_THREAT_TO_THEMSELVES_OR_OTHER",
    DRIVER_IS_BEHAVING_INAPPROPRIATELY= "DRIVER_IS_BEHAVING_INAPPROPRIATELY",
    OTHER = "OTHER",
}