export enum FlagInappropriateJob {
    INAPPROPRIATE_OR_INACCURATE_PHOTOS = "INAPPROPRIATE_OR_INACCURATE_PHOTOS",
    INAPPROPRIATE_WRITTEN_CONTENT = "INAPPROPRIATE_WRITTEN_CONTENT",
    INAPPROPRIATE_JOB_DESCRIPTION_OR_COMPANY = "INAPPROPRIATE_JOB_DESCRIPTION_OR_COMPANY",
    OTHER = "OTHER",
}