export enum CompanyPreferenceJotformLabel {
    CDL_CLASS = "CDL_CLASS",
    OWNER_OPERATOR = "OWNER_OPERATOR",
    DRUG_TEST_PASS = "DRUG_TEST_PASS",
    MINIMUM_ACCIDENTS = "MINIMUM_ACCIDENTS",
    MIN_MOVING_VIOLATIONS = "MINIMUM_MOVING_VIOLATIONS",
    YEARS_CDL_EXPERIENCE = "YEARS_CDL_EXPERIENCE",
    EMPLOYMENT_TYPE = "EMPLOYMENT_TYPE",
    JOB_GEOGRAPHY = "JOB_GEOGRAPHY",
}