export enum CompanyPreferenceAutoRecrutingLabel {
    ENROLL_IN_AUTO_RECRUITING = "ENROLL_IN_AUTO_RECRUITING",
    PARTICIPATE_IN_REFER_BACK_PROGRAM = "PARTICIPATE_IN_REFER_BACK_PROGRAM",
    AUTO_ASSIGN_INBOUND_APPLICANTS = "AUTO_ASSIGN_INBOUND_APPLICANTS",
    AUTO_ASSIGN_METHOD = "AUTO_ASSIGN_METHOD",
}