export enum CompanyPreferenceCategory {
    JOTFORM = 'JOTFORM',
    AUTO_RECRUITING = "AUTO_RECRUITING",
    ENHANCEMENT = "ENHANCEMENT",
    VOE = "VOE",
    ONBOARDING_CHECKLIST = "ONBOARDING_CHECKLIST",
}
