export enum CompanyPreferenceATSIntegrationLabel {
  CONFLICT_RESOLUTION_STRATEGY = 'CONFLICT_RESOLUTION_STRATEGY',
  ALLOW_MERGE_WITH_MANUAL_APPLICANTS = 'ALLOW_MERGE_WITH_MANUAL_APPLICANTS',
  AUTO_EXPORT_CAMPAIGN_ACTIVITIES = 'AUTO_EXPORT_CAMPAIGN_ACTIVITIES',
  SYNC_INTERVAL_MINUTES = 'SYNC_INTERVAL_MINUTES',
}

export enum ConflictResolutionStrategy {
  ATS_WINS = 'ATS_WINS',
  DRIVERFLY_WINS = 'DRIVERFLY_WINS',
  NEWEST_WINS = 'NEWEST_WINS',
  MANUAL = 'MANUAL',
}
