export enum CompanyPreferenceOnboardingChecklistLabel {
	APPLICANT_DOCUMETS = "APPLICANT_DOCUMETS",
	APPLICANT_DAC = "APPLICANT_DAC",
	EMPLOYEE_DQF_DOCUMENTS = "EMPLOYEE_DQF_DOCUMENTS",
	EMPLOYEE_HR_FILES = "EMPLOYEE_HR_FILES",

}
