export enum OtherRequirementType {
  HEALTH_BENEFITS = "HEALTH_BENEFITS",
  LEASE_TO_OWN_PROGRAM = "LEASE_TO_OWN_PROGRAM",
  DROP_AND_HOOK_ONLY = "DROP_AND_HOOK_ONLY",
  CPM_PAYMENT = "CPM_PAYMENT",
  TEAM_DRIVERS = "TEAM_DRIVERS",
  PAID_TRAINING = "PAID_TRAINING",
  OTHERS = "OTHERS",
}
