export enum UserPreferenceCommunicationLabel {
    PREFERRED_METHOD = "PREFERRED_METHOD",
    PREFERRED_HOURS = "PREFERRED_HOURS",
    RECEIVE_SUGGESTED_JOBS = "RECEIVE_SUGGESTED_JOBS",
    RECEIVE_NEWSLETTER = "RECEIVE_NEWSLETTER",
    RECEIVE_DRIVERFLY = "RECEIVE_DRIVERFLY"
}