import * as yup from 'yup';
import { ATSProvider } from '../../enums/integrations/ats-provider.enum';
import { SyncDirection } from '../../enums/integrations/sync-direction.enum';
import { CompanyEntity } from '../company/company.entity';
import { UserEntity } from '../user/user.entity';
import { ATSCredentials, FieldMappingConfig } from './ats-provider.interface';

export class IntegrationConnectionEntity {
  id?: number;
  company?: CompanyEntity;
  companyId?: number;

  provider?: ATSProvider;
  isActive?: boolean;

  // Encrypted credentials (stored encrypted in backend)
  credentials?: ATSCredentials;

  // Sync configuration
  syncDirection?: SyncDirection;
  autoSyncEnabled?: boolean;
  syncIntervalMinutes?: number; // for polling-based sync
  lastSyncAt?: Date;
  lastSuccessfulSyncAt?: Date;

  // Webhook configuration
  webhookEnabled?: boolean;
  webhookSecret?: string; // for signature verification
  webhookUrl?: string; // generated by DriverFly

  // Field mapping configuration
  fieldMappingConfig?: FieldMappingConfig;

  // Metadata
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: UserEntity;
  createdById?: number;

  static yupSchema(t: (key: string) => string) {
    return yup.object({
      provider: yup
        .mixed<ATSProvider>()
        .oneOf(Object.values(ATSProvider))
        .required(t('PROVIDER_REQUIRED')),
      isActive: yup.boolean().default(true),
      credentials: yup.object().required(t('CREDENTIALS_REQUIRED')),
      syncDirection: yup
        .mixed<SyncDirection>()
        .oneOf(Object.values(SyncDirection))
        .default(SyncDirection.BIDIRECTIONAL),
      autoSyncEnabled: yup.boolean().default(false),
      syncIntervalMinutes: yup.number().min(5).max(1440).nullable(),
      webhookEnabled: yup.boolean().default(false),
      webhookSecret: yup.string().nullable(),
      fieldMappingConfig: yup.object().nullable(),
    });
  }
}

export interface CreateConnectionDto {
  provider: ATSProvider;
  credentials: ATSCredentials;
  syncDirection?: SyncDirection;
  autoSyncEnabled?: boolean;
  webhookEnabled?: boolean;
}

export interface UpdateConnectionDto {
  isActive?: boolean;
  credentials?: ATSCredentials;
  syncDirection?: SyncDirection;
  autoSyncEnabled?: boolean;
  syncIntervalMinutes?: number;
  webhookEnabled?: boolean;
  fieldMappingConfig?: FieldMappingConfig;
}

export interface TestConnectionDto {
  provider: ATSProvider;
  credentials: ATSCredentials;
}
