export enum EmployeeReasonCodeNotQualified {
    CDL_CLASS_TYPE_HOLDER = "CDL_CLASS_TYPE_HOLDER",
    YEARS_CDL_EXPERIENCE = "YEARS_CDL_EXPERIENCE",
    SPECIFIC_EQUIPMENT_EXPERIENCE = "SPECIFIC_EQUIPMENT_EXPERIENCE",
    BAD_MVR = "BAD_MVR",
    INSUFFICIENT_DOCUMENTATION = "INSUFFICIENT_DOCUMENTATION",
    MINIMUM_AGE_REQUIREMENTS = "MINIMUM_AGE_REQUIREMENTS",
    CRIMINAL_OFFENSE = "CRIMINAL_OFFENSE",
    INAPPROPRIATE_BEHAVIOR = "INAPPROPRIATE_BEHAVIOR",
    CITIZENSHIP = "CITIZENSHIP",
    ENDORSEMENTS = "ENDORSEMENTS",
    FAILED_DRUG_TEST = "FAILED_DRUG_TEST",
    OTHER = "OTHER",
}

export enum EmployeeReasonCodeNotInterested {
    PAY_RATE = "PAY_RATE",
    PAY_STRUCTURE = "PAY_STRUCTURE",
    SCHEDULE = "SCHEDULE",
    EMPLOYMENT_STATUS_TYPE = "EMPLOYMENT_STATUS_TYPE",
    LOOKING_FOR_OWNER_OP_ROLE = "LOOKING_FOR_OWNER_OP_ROLE",
    TEAM_DRIVER = "TEAM_DRIVER",
    EQUIPMENT_TYPE = "EQUIPMENT_TYPE",
    BETTER_OFFER_ELSEWHERE = "BETTER_OFFER_ELSEWHERE",
    GEOGRAPHY_COVERED = "GEOGRAPHY_COVERED",
    DELIVERY_MODE = "DELIVERY_MODE",
    OTHER = "OTHER",
}

export enum EmployeeReasonCodeQuit {
    MISSING_PAY = "MISSING_PAY",
    UNSAFE_WORKING_CONDITIONS = "UNSAFE_WORKING_CONDITIONS",
    PAY_RATE = "PAY_RATE",
    PAY_STRUCTURE = "PAY_STRUCTURE",
    SCHEDULE = "SCHEDULE",
    EMPLOYMENT_STATUS_TYPE = "EMPLOYMENT_STATUS_TYPE",
    LOOKING_FOR_OWNER_OP_ROLE = "LOOKING_FOR_OWNER_OP_ROLE",
    TEAM_DRIVER = "TEAM_DRIVER",
    EQUIPMENT_TYPE = "EQUIPMENT_TYPE",
    BETTER_OFFER_ELSEWHERE = "BETTER_OFFER_ELSEWHERE",
    GEOGRAPHY_COVERED = "GEOGRAPHY_COVERED",
    DELIVERY_MODE = "DELIVERY_MODE",
    OTHER = "OTHER",
}

export enum EmployeeReasonCodeFired {
    TOO_INEXPERIENCED = "TOO_INEXPERIENCED",
    UNSAFE_DRIVING_BEHAVIOR = "UNSAFE_DRIVING_BEHAVIOR",
    VEHICLE_DAMAGE = "VEHICLE_DAMAGE",
    NO_SHOW = "NO_SHOW",
    VIOLATIONS = "VIOLATIONS",
    INSUFFICIENT_DOCUMENTATION = "INSUFFICIENT_DOCUMENTATION",
    INAPPROPRIATE_BEHAVIOR = "INAPPROPRIATE_BEHAVIOR",
    INABILITY_TO_MEET_JOB_SPECIFICATIONS = "INABILITY_TO_MEET_JOB_SPECIFICATIONS",
    FAILED_DRUG_TEST = "FAILED_DRUG_TEST",
    OTHER = "OTHER",
}
