export enum EmployeeOnBoardingChecklist {
    DRUG_ALCOHOL_CHAIN_CUSTODY = 'DRUG_ALCOHOL_CHAIN_CUSTODY',
    BACKGROUND_CHECK = 'BACKGROUND_CHECK',
    DRIVER_AUTHORIZATION = 'DRIVER_AUTHORIZATION',
    SIGNED_HOURS_OF_SERVICE_RECORD = 'SIGNED_HOURS_OF_SERVICE_RECORD',
    INSURANCE_PASS = 'INSURANCE_PASS',
    CONTRACT_SIGNED = 'CONTRACT_SIGNED',
    TRUCK_PROVIDED = 'TRUCK_PROVIDED',
    ORIENTATION_COMPLETE = 'ORIENTATION_COMPLETE'
}