import { UserEntity } from '../user/user.entity';
import { CompanyEntity } from '../company/company.entity';
import { JobEntity } from '../job/job.entity';
import { DocumentEntity } from '../documents/document.entity';
import { ApplicantExperienceEntity } from './applicant-experience.entity';
import { DriverLicenseType } from '../../enums/drivers/driver-license-type.enum';
import { ApplicantEquipmentEntity } from './applicant-equipment.entity';
import { DriverDegree } from '../../enums/drivers/driver-degree.enum';
import { ApplicantEmployerEntity } from './applicant-employer.entity';

export interface ApplicantEntity {
  id?: number;
  version?: number;
  user?: UserEntity;
  company?: CompanyEntity;
  job?: JobEntity;
  status?: string;
  first_name?: string;
  last_name?: string;
  phone?: string;
  email?: string;
  birthdate?: string;
  street?: string;
  city?: string;
  state?: string;
  zip_code?: string;
  resume?: DocumentEntity;
  drivers_license?: DocumentEntity;
  medical_card?: DocumentEntity;
  license_number?: string;
  license_expiry?: string;
  license_state?: string;
  license_type?: DriverLicenseType;
  years_cdl_experience?: number;
  can_pass_drug_test?: boolean;
  is_owner_operator?: boolean;
  highest_degree?: DriverDegree;
  emergency_contact_name?: string;
  emergency_contact_number?: string;
  emergency_contact_relationship?: string;
  has_past_dui?: boolean;
  dui_years?: string[];
  criminal_history?: string;
  accident_count?: number;
  accident_details?: string;
  license_revoked?: boolean;
  license_revoked_details?: string;
  psp_violations?: boolean;
  psp_violations_details?: string;
  tickets?: boolean;
  tickets_details?: string;
  positive_drug_test?: boolean;
  positive_drug_test_details?: string;
  equipment_experience?: ApplicantExperienceEntity[];
  equipment_owned?: ApplicantEquipmentEntity[];
  employers?: ApplicantEmployerEntity[];
  created_at?: string;
  last_updated_at?: string;
}
