export enum DocumentReminderType {
  SAFETY_INSPECTION = 'SAFETY_INSPECTION',
  MAINTENANCE_REPORT = 'MAINTENANCE_REPORT',
  REGISTRATION_EXPIRATION = 'REGISTRATION_EXPIRATION',
  INSURANCE_EXPIRATION = 'INSURANCE_EXPIRATION',
  REPAIR_UPDATES = 'REPAIR_UPDATES',
  OTHER = 'OTHER',
}
