export enum RouteType {
  LOCAL = "LOCAL",
  REGIONAL_NIGHT = "REGIONAL_NIGHT",
  REGIONAL_WEEKEND = "REGIONAL_WEEKEND",
  REGIONAL_ROAD = "REGIONAL_ROAD",
  OTR_WEEKEND = "OTR_WEEKEND",
  OTR_ROAD = "OTR_ROAD",
}
