export enum VehicleAccessory {
    DROP_TRAILER = 'DROP_TRAILER',
    CARBON_COMPLIANT = 'CARBON_COMPLIANT',
    CHAINS = 'CHAINS',
    CONESTOGA = 'CONESTOGA',
    DOUBLES = 'DOUBLES',
    FLOAT = 'FLOAT',
    LIFT_GATE = 'LIFT_GATE',
    MATERIAL_HANDLING_EQUIPMENT = 'MATERIAL_HANDLING_EQUIPMENT',
    TARPS = 'TARPS',
    SAND_BLOWER = 'SAND_BLOWER',
    OTHER = 'OTHER',
  }
  