import { DriverEndorsement } from '../../enums/drivers/driver-endorsement.enum';
import { DriverDegree } from '../../enums/drivers/driver-degree.enum';
import { DriverLicenseType } from '../../enums/drivers/driver-license-type.enum';
import { JobBenefits } from '../../enums/jobs/job-benefits.enum';
import { JobDeliveryType } from '../../enums/jobs/job-delivery-type.enum';
import { JobEquipmentType } from '../../enums/jobs/job-equipment-type.enum';
import { JobGeography } from '../../enums/jobs/job-geography.enum';
import { JobPayMethod } from '../../enums/jobs/job-pay-method.enum';
import { JobSchedule } from '../../enums/jobs/job-schedule.enum';
import { JobTeamDriver } from '../../enums/jobs/job-team-driver.enum';
import { JobEmploymentType } from '../../enums/jobs/job-employment-type.enum';
import { LocationEntity } from '../company/location.entity';
import VehicleEntity from '../company/vehicle.entity';
import { JobCriminalEntity } from "./job-criminal.entity";
import { JobEquipmentEntity } from "./job-equipment.entity";
import { JobMvrEntity } from './job-mvr.entity';
import { JobSkillEntity } from './job-skill.entity';
import { CompanyEntity } from '../company/company.entity';

export interface JobEntity {
  id?: number,
  location: LocationEntity;
  company: CompanyEntity;
  title: string;
  description: string;
  description_short?: string;
  drivers_needed?: number;
  expiry_date?: string | Date;
  geography?: JobGeography;
  schedule?: JobSchedule;
  schedule_other?: string;
  employment_type?: JobEmploymentType;
  equipment_type?: JobEquipmentType[];
  equipment_type_other?: string;
  delivery_type?: JobDeliveryType[];
  team_drivers?: JobTeamDriver;
  pay_method?: JobPayMethod;
  min_salary?: number;
  max_salary?: number;
  min_rate?: number;
  max_rate?: number;
  min_miles?: number;
  max_miles?: number;
  min_hours?: number;
  max_hours?: number;
  min_percent?: number;
  max_percent?: number;
  min_weekly_pay?: number;
  max_weekly_pay?: number;
  benefits?: JobBenefits[];
  benefits_other?: string;
  vehicles?: VehicleEntity[];
  cdl_class?: DriverLicenseType[];
  min_years_experience?: number;
  min_degree?: DriverDegree;
  required_skills?: JobSkillEntity[];
  required_skills_other?: string;
  required_equipment?: JobEquipmentEntity[];
  required_endorsement?: DriverEndorsement[];
  transmission_type_experience?: string;
  max_applicant_radius?: number;
  must_pass_drug_test?: boolean;
  must_have_clean_mvr?: boolean;
  mvr_requirements?: JobMvrEntity[];
  accept_sap_graduates?: boolean;
  must_have_clean_criminal_history?: boolean;
  criminal_history?: JobCriminalEntity[];
  max_accidents?: number;
  safety_requirements_other?: string;
  created_at?: string | Date;
}
