export enum HearAboutUsType {
	REFERRAL = "REFERRAL",
	FRIENDS = "FRIENDS",
	JOB_BOARD = "JOB_BOARD",
	SOCIAL_MEDIA = "SOCIAL_MEDIA",
	EMAIL = "EMAIL",
	PRINT_AD = "PRINT_AD",
	WORLD_OF_MOUTH = "WORLD_OF_MOUTH",
	OTHER = "OTHER",
}
