export enum InappropriateJobFlag {
    INAPPROPRIATE_OR_INACCURATE_PHOTOS = "INAPPROPRIATE_OR_INACCURATE_PHOTOS",
    INAPPROPRIATE_WRITTEN_CONTENT = "INAPPROPRIATE_WRITTEN_CONTENT",
    INAPPROPRIATE_JOB_DESCRIPTION_OR_COMPANY = "INAPPROPRIATE_JOB_DESCRIPTION_OR_COMPANY",
    OTHER = "OTHER",
    DRIVER_IS_NOT_WHO_THEY_SAY_THEY_ARE = "DRIVER_IS_NOT_WHO_THEY_SAY_THEY_ARE",
    DRIVER_IS_A_THREAT_TO_THEMSELVES_OR_OTHER = "DRIVER_IS_A_THREAT_TO_THEMSELVES_OR_OTHER",
    DRIVER_IS_BEHAVING_INAPPROPRIATELY= "DRIVER_IS_BEHAVING_INAPPROPRIATELY",
}