export enum SyncStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL',
}

export enum SyncType {
  FULL_IMPORT = 'FULL_IMPORT',
  INCREMENTAL_IMPORT = 'INCREMENTAL_IMPORT',
  WEBHOOK_EVENT = 'WEBHOOK_EVENT',
  CAMPAIGN_EXPORT = 'CAMPAIGN_EXPORT',
}

export enum ATSActivityExportStatus {
  PENDING = 'PENDING',
  EXPORTED = 'EXPORTED',
  FAILED = 'FAILED',
}
